# Generated by Django 5.2 on 2025-05-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsArticle',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='NewsSite',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='site',
            new_name='source',
        ),
    ]
